# ARTIFICIAL NEURAL NETWORK

## DATA PREPROCESSING

### Importing the libraries

In [ ]:
#pip install scikeras

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.16.1'

### Importing the dataset

In [3]:
dataset = pd.read_excel("C:/Users/Latitude/Desktop/Mushroom Classification/Mushroom.xlsx")
order = np.arange(1, 21, 1).tolist()
neworder = order + [0]
dataset = dataset[dataset.columns[neworder]]
len(dataset.columns)

21

## Dealing with NAs

Find Missing Values Per Column and Eliminate the Columns

In [4]:
percent_missing = dataset.isnull().sum() * 100 / len(dataset)
print(percent_missing)

dataset = dataset.dropna(axis = 1)
len(dataset.columns)

cap-diameter             0.000000
cap-shape                0.000000
cap-surface             23.121387
cap-color                0.000000
does-bruise-or-bleed     0.000000
gill-attachment         16.184971
gill-spacing            41.040462
gill-color               0.000000
stem-height              0.000000
stem-width               0.000000
stem-root               84.393064
stem-surface            62.427746
stem-color               0.000000
veil-type               94.797688
veil-color              87.861272
has-ring                 0.000000
ring-type                4.046243
spore-print-color       89.595376
habitat                  0.000000
season                   0.000000
class                    0.000000
dtype: float64


12

Check whether the columns were eliminated

In [5]:
percent_missing = dataset.isnull().sum() * 100 / len(dataset)
print(percent_missing)

cap-diameter            0.0
cap-shape               0.0
cap-color               0.0
does-bruise-or-bleed    0.0
gill-color              0.0
stem-height             0.0
stem-width              0.0
stem-color              0.0
has-ring                0.0
habitat                 0.0
season                  0.0
class                   0.0
dtype: float64


## Encoding Categorical Data

Filter Columns with Categorical Data

In [6]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [7]:
cols1 = np.arange(1, 5, 1).tolist()
cols2 = np.arange(7, 11, 1).tolist()
cols = cols1 + cols2

Xnew = X[:, cols]
print(cols)

[1, 2, 3, 4, 7, 8, 9, 10]


In [8]:
print(Xnew[:10])

[['x' 'o' 'f' 'w' 'w' 't' 'd' 'w']
 ['x' 'o' 'f' 'w' 'w' 't' 'd' 'u']
 ['x' 'o' 'f' 'w' 'w' 't' 'd' 'w']
 ['f' 'e' 'f' 'w' 'w' 't' 'd' 'w']
 ['x' 'o' 'f' 'w' 'w' 't' 'd' 'w']
 ['x' 'o' 'f' 'w' 'w' 't' 'd' 'u']
 ['f' 'o' 'f' 'w' 'w' 't' 'd' 'w']
 ['x' 'e' 'f' 'w' 'w' 't' 'd' 'u']
 ['f' 'o' 'f' 'w' 'w' 't' 'd' 'a']
 ['f' 'e' 'f' 'w' 'w' 't' 'd' 'w']]


Encoding the categorical data

In [9]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [10]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1, 2, 3, 4, 7, 8, 9, 10])], remainder='passthrough')
X = ct.fit_transform(X)

In [11]:
print(X[:10])

  (0, 6)	1.0
  (0, 13)	1.0
  (0, 19)	1.0
  (0, 31)	1.0
  (0, 44)	1.0
  (0, 47)	1.0
  (0, 48)	1.0
  (0, 59)	1.0
  (0, 60)	15.26
  (0, 61)	16.95
  (0, 62)	17.09
  (1, 6)	1.0
  (1, 13)	1.0
  (1, 19)	1.0
  (1, 31)	1.0
  (1, 44)	1.0
  (1, 47)	1.0
  (1, 48)	1.0
  (1, 58)	1.0
  (1, 60)	16.6
  (1, 61)	17.99
  (1, 62)	18.19
  (2, 6)	1.0
  (2, 13)	1.0
  (2, 19)	1.0
  :	:
  (7, 60)	14.86
  (7, 61)	17.03
  (7, 62)	17.44
  (8, 2)	1.0
  (8, 13)	1.0
  (8, 19)	1.0
  (8, 31)	1.0
  (8, 44)	1.0
  (8, 47)	1.0
  (8, 48)	1.0
  (8, 56)	1.0
  (8, 60)	12.85
  (8, 61)	17.27
  (8, 62)	18.69
  (9, 2)	1.0
  (9, 8)	1.0
  (9, 19)	1.0
  (9, 31)	1.0
  (9, 44)	1.0
  (9, 47)	1.0
  (9, 48)	1.0
  (9, 59)	1.0
  (9, 60)	13.55
  (9, 61)	16.04
  (9, 62)	16.88


In [12]:
print(y)

[1 1 1 ... 1 1 1]


### Splitting the dataset into the Training set and Test set

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

### Feature Scaling

In [14]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler(with_mean = False)
X_train[:, :-1] = sc.fit_transform(X_train[:, :-1])
X_test[:, :-1] = sc.transform(X_test[:, :-1])

## BUILDING, FITTING, AND EVALUATING THE MODEL

## Building the ANN

### Initializing the ANN

In [15]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [16]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [17]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [18]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## Training the ANN

### Compiling the ANN

In [19]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

### Training the ANN on the Training set

In [20]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)#95.26% Accuracy

Epoch 1/100
1527/1527 ━━━━━━━━━━━━━━━━━━━━ 8s 3ms/step - accuracy: 0.6640 - loss: 0.6126
Epoch 2/100
1527/1527 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.8224 - loss: 0.3980
Epoch 3/100
1527/1527 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.8718 - loss: 0.3014
Epoch 4/100
1527/1527 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.8933 - loss: 0.2592
Epoch 5/100
1527/1527 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.9133 - loss: 0.2253
Epoch 6/100
1527/1527 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.9235 - loss: 0.2045
Epoch 7/100
1527/1527 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.9279 - loss: 0.1950
Epoch 8/100
1527/1527 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - accuracy: 0.9308 - loss: 0.1820
Epoch 9/100
1527/1527 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.9338 - loss: 0.1772
Epoch 10/100
1527/1527 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.9351 - loss: 0.1761
Epoch 11/100
1527/1527 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.9361 - loss: 0.1724
Epoch 12/100
1527/1

## Making the predictions and evaluating the model

### Predicting the Test set results

In [41]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

382/382 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step
[[1 0]
 [0 1]
 [1 1]
 ...
 [0 0]
 [1 1]
 [0 0]]


### Making the Confusion Matrix

In [42]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)#95.59% Accuracy

[[5111  191]
 [ 348 6564]]


0.955870312755854

## Applying K-Fold Cross Validation

In [36]:
from sklearn.model_selection import cross_val_score
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

# Define the Keras model
def build_model():
    model = Sequential([
        Dense(10, activation='relu', input_shape=(X_train.shape[1],)),
        Dense(10, activation='relu'),
        Dense(1, activation='sigmoid')
    ])
    model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
    return model

# Wrap the Keras model in a sklearn Pipeline with StandardScaler
estimators = []
estimators.append(('standardize', StandardScaler(with_mean = False)))
estimators.append(('mlp', KerasClassifier(build_fn=build_model, epochs=100, verbose=0)))
pipeline = Pipeline(estimators)
#Scikit-Learn's Pipeline allows us to chain multiple transformers and an estimator into a single object.
#In this case, we create a pipeline with two steps:
#1. The first step (standardize) applies StandardScaler() to standardize the input features.
#2. The second step ("mlp") is our Keras model wrapped inside "KerasClassifier". We specify the "build_model" function as the model-building function, along with parameters like "epochs = 1" and "verbose = 0"
#Advantages:
#1. This approach integrates the Keras model seamlessly into Scikit-Learn's cross-validation framework.
#2. By using a Pipeline, we ensure that data preprocessing steps (such as feature scaling) are applied consistently during each fold of cross-validation.
#3. Using cross_val_score with the pipeline simplifies the cross-validation process and ensures that the error encountered with KerasClassifier is avoided.

# Use cross_val_score with the Pipeline
accuracies = cross_val_score(pipeline, X_train, y_train, cv=10, scoring='accuracy')


c:\Users\Latitude\AppData\Local\Programs\Python\Python312\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
c:\Users\Latitude\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
c:\Users\Latitude\AppData\Local\Programs\Python\Python312\Lib\site-packages\scikeras\wrappers.py:925: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)
c:\Users\Latitude\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src

In [37]:
print(accuracies)

[0.98567335 0.97032337 0.9768727  0.98342202 0.98690135 0.9825998
 0.98689867 0.98505629 0.9825998  0.98628454]


In [38]:
#Take mean of all the accuracies
accuracies.mean() #98.27%

0.9826631895026461

In [39]:
#Standard Deviation of the Accuracies to find variance
accuracies.std() #<0.01% Variance. That is good (Low Bias and Low Variance)

0.00500188247499076